name: terraform-enterprise-template

on:
  pull_request:
  push:
    branches: ["main"]

env:
  TF_VERSION: "1.6.6"
  TF_DIR: "examples/single-region"

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform fmt
        run: terraform fmt -recursive -check
      - name: Terraform validate
        run: |
          cd "${TF_DIR}"
          terraform init -backend=false -input=false
          terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v3
      - name: TFLint
        run: |
          tflint --init
          tflint -f compact

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Conftest
        run: |
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin
      - name: Conftest policy gate
        run: conftest test -p policies "${TF_DIR}"

  plan:
    runs-on: ubuntu-latest
    needs: [fmt-validate, tflint, checkov, policy]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform plan
        run: |
          cd "${TF_DIR}"
          terraform init -input=false
          terraform plan -out=tfplan
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: [plan]
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_DIR }}
      - name: Terraform apply
        run: |
          cd "${TF_DIR}"
          terraform apply -input=false tfplan
