stages:
  - validate
  - policy
  - plan
  - approval
  - apply

variables:
  TF_VERSION: "1.6.6"
  TF_DIR: "examples/single-region"

validate:
  stage: validate
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - terraform fmt -recursive -check
    - cd "${TF_DIR}"
    - terraform init -backend=false -input=false
    - terraform validate

policy:
  stage: policy
  image: alpine:3.19
  script:
    - apk add --no-cache curl tar
    - curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
    - tar -xzf conftest.tar.gz
    - mv conftest /usr/local/bin/conftest
    - conftest test -p policies "${TF_DIR}"

plan:
  stage: plan
  image: hashicorp/terraform:${TF_VERSION}
  script:
    - cd "${TF_DIR}"
    - terraform init -input=false
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_DIR}/tfplan

approval:
  stage: approval
  when: manual
  script:
    - echo "Manual approval required"

apply:
  stage: apply
  image: hashicorp/terraform:${TF_VERSION}
  dependencies:
    - plan
  script:
    - cd "${TF_DIR}"
    - terraform apply -input=false tfplan
  when: manual
